"""
app/reports/pdf_generator.py — PDF report generator using ReportLab.

ReportLab works on all platforms with no system dependencies.

Usage:
    from app.reports.pdf_generator import generate_pdf, save_pdf
    pdf_bytes = generate_pdf(report=report, user=user)
"""

import os
from io import BytesIO
from datetime import datetime
from typing import Optional

from flask import current_app
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, KeepTogether, Image
)
from reportlab.platypus import BaseDocTemplate, Frame, PageTemplate
from reportlab.lib.colors import HexColor


# ── Colour helpers ─────────────────────────────────────────────────────────────

def _hex(hex_str: str) -> HexColor:
    """Convert a CSS hex colour string to a ReportLab HexColor."""
    hex_str = hex_str.strip()
    if not hex_str.startswith("#"):
        hex_str = "#" + hex_str
    try:
        return HexColor(hex_str)
    except Exception:
        return HexColor("#4F46E5")


COLOR_GREEN  = HexColor("#10b981")
COLOR_YELLOW = HexColor("#f59e0b")
COLOR_RED    = HexColor("#ef4444")
COLOR_GRAY   = HexColor("#6b7280")
COLOR_LIGHT  = HexColor("#f3f4f6")
COLOR_WHITE  = colors.white
COLOR_BLACK  = HexColor("#1f2937")


def _score_color(score: Optional[int]) -> HexColor:
    if score is None:
        return COLOR_GRAY
    if score >= 80:
        return COLOR_GREEN
    if score >= 50:
        return COLOR_YELLOW
    return COLOR_RED


def _status_color(status: str) -> HexColor:
    return {"pass": COLOR_GREEN, "warning": COLOR_YELLOW, "fail": COLOR_RED}.get(
        status, COLOR_GRAY
    )


def _status_icon(status: str) -> str:
    return {"pass": "PASS", "warning": "WARN", "fail": "FAIL"}.get(status, "—")


# ── Public API ─────────────────────────────────────────────────────────────────

def generate_pdf(report, user) -> bytes:
    """
    Render the SEO report as a PDF and return raw bytes.

    Args:
        report: Report model instance (must have .items and .client loaded).
        user:   User model instance (for brand colour).

    Returns:
        PDF file contents as bytes.
    """
    buffer = BytesIO()
    brand = _hex(user.brand_color or "#4F46E5")

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
        title=f"SEO Report — {report.client.name}",
        author=user.agency_name or user.full_name,
    )

    story = []
    styles = _build_styles(brand)

    # ── Cover ──────────────────────────────────────────────────────────────
    story += _build_cover(report, user, brand, styles)
    story.append(Spacer(1, 6 * mm))

    # ── Score summary ──────────────────────────────────────────────────────
    story += _build_scores(report, brand, styles)
    story.append(Spacer(1, 6 * mm))

    # ── Quick facts table ──────────────────────────────────────────────────
    story += _build_facts(report, brand, styles)
    story.append(Spacer(1, 6 * mm))

    # ── Checks by category ─────────────────────────────────────────────────
    categories = [
        ("performance", "Performance"),
        ("seo",         "On-Page SEO"),
        ("technical",   "Technical"),
        ("content",     "Content"),
    ]
    groups = _group_checks(report)
    for key, label in categories:
        items = groups.get(key, [])
        if items:
            story += _build_category(label, items, brand, styles)
            story.append(Spacer(1, 4 * mm))

    # ── Footer note ────────────────────────────────────────────────────────
    story.append(HRFlowable(width="100%", thickness=0.5, color=COLOR_LIGHT))
    story.append(Spacer(1, 2 * mm))
    agency = user.agency_name or user.full_name
    date_str = report.created_at.strftime("%Y-%m-%d")
    story.append(Paragraph(
        f"Generated by {agency} · {date_str} · SEO Report",
        styles["footer"],
    ))

    doc.build(story)
    return buffer.getvalue()


def save_pdf(report, user) -> str:
    """Generate PDF, save to disk, and return the filename."""
    pdf_bytes = generate_pdf(report, user)
    filename = f"report_{report.id}_{report.client_id}.pdf"
    upload_dir = _ensure_upload_dir()
    with open(os.path.join(upload_dir, filename), "wb") as f:
        f.write(pdf_bytes)
    return filename


def get_pdf_path(filename: str) -> str:
    """Return the absolute filesystem path for a stored PDF."""
    return os.path.join(_ensure_upload_dir(), filename)


# ── Internal builders ──────────────────────────────────────────────────────────

def _ensure_upload_dir() -> str:
    # Use REPORT_FOLDER from config if set; fall back to static/reports.
    upload_dir = current_app.config.get(
        "REPORT_FOLDER",
        os.path.join(current_app.static_folder, "reports"),
    )
    os.makedirs(upload_dir, exist_ok=True)
    return upload_dir


def _group_checks(report) -> dict:
    groups: dict = {}
    for item in report.items.all():
        groups.setdefault(item.category, []).append(item)
    return groups


def _build_styles(brand: HexColor) -> dict:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "title",
            fontSize=22, textColor=COLOR_WHITE, fontName="Helvetica-Bold",
            leading=26, alignment=TA_LEFT,
        ),
        "subtitle": ParagraphStyle(
            "subtitle",
            fontSize=10, textColor=COLOR_WHITE, fontName="Helvetica",
            leading=14, alignment=TA_LEFT,
        ),
        "agency": ParagraphStyle(
            "agency",
            fontSize=11, textColor=COLOR_WHITE, fontName="Helvetica-Bold",
            leading=14, alignment=TA_LEFT,
        ),
        "section": ParagraphStyle(
            "section",
            fontSize=13, textColor=brand, fontName="Helvetica-Bold",
            leading=18, spaceBefore=4,
        ),
        "check_name": ParagraphStyle(
            "check_name",
            fontSize=10, textColor=COLOR_BLACK, fontName="Helvetica-Bold",
            leading=14,
        ),
        "check_detail": ParagraphStyle(
            "check_detail",
            fontSize=9, textColor=COLOR_GRAY, fontName="Helvetica",
            leading=13,
        ),
        "check_rec": ParagraphStyle(
            "check_rec",
            fontSize=8.5, textColor=HexColor("#9ca3af"), fontName="Helvetica-Oblique",
            leading=12,
        ),
        "footer": ParagraphStyle(
            "footer",
            fontSize=8, textColor=COLOR_GRAY, fontName="Helvetica",
            alignment=TA_CENTER,
        ),
        "score_big": ParagraphStyle(
            "score_big",
            fontSize=36, fontName="Helvetica-Bold",
            alignment=TA_CENTER, leading=40,
        ),
        "score_small": ParagraphStyle(
            "score_small",
            fontSize=22, fontName="Helvetica-Bold",
            alignment=TA_CENTER, leading=26,
        ),
        "score_label": ParagraphStyle(
            "score_label",
            fontSize=8, fontName="Helvetica",
            alignment=TA_CENTER, textColor=COLOR_GRAY,
            leading=12, spaceBefore=2,
        ),
    }


def _build_cover(report, user, brand: HexColor, styles: dict) -> list:
    """Build a coloured cover header block with logo if available."""
    agency = user.agency_name or user.full_name
    url = report.client.website_url
    date_str = report.created_at.strftime("%B %d, %Y")

    # Try to embed the logo image from disk
    logo_cell = None
    if user.logo_filename:
        logo_path = os.path.join(
            current_app.static_folder, "uploads", user.logo_filename
        )
        if os.path.exists(logo_path):
            try:
                logo_cell = Image(logo_path, width=40 * mm, height=14 * mm,
                                  kind="proportional")
            except Exception:
                logo_cell = None

    if logo_cell is None:
        logo_cell = Paragraph(agency, styles["agency"])

    cover_data = [
        [
            logo_cell,
            Paragraph("SEO Report", styles["agency"]),
        ],
        [
            Paragraph(report.client.name, styles["title"]),
            "",
        ],
        [
            Paragraph(url, styles["subtitle"]),
            Paragraph(f"Generated {date_str}", styles["subtitle"]),
        ],
    ]

    t = Table(cover_data, colWidths=["65%", "35%"])
    t.setStyle(TableStyle([
        ("BACKGROUND",   (0, 0), (-1, -1), brand),
        ("ROWPADDING",   (0, 0), (-1, -1), 6),
        ("TOPPADDING",   (0, 0), (-1, 0),  10),
        ("BOTTOMPADDING",(0, -1),(-1, -1), 10),
        ("LEFTPADDING",  (0, 0), (-1, -1), 14),
        ("RIGHTPADDING", (0, 0), (-1, -1), 14),
        ("SPAN",         (0, 1), (1, 1)),
        ("VALIGN",       (0, 0), (-1, -1), "MIDDLE"),
        ("ROUNDEDCORNERS", [6]),
    ]))
    return [t]


def _build_scores(report, brand: HexColor, styles: dict) -> list:
    """Build the score summary row."""
    overall_color = _score_color(report.overall_score)

    def score_cell(value, label, color):
        return [
            Paragraph(str(value) if value is not None else "—",
                      ParagraphStyle("sc", fontSize=28 if label == "Overall" else 20,
                                     fontName="Helvetica-Bold", alignment=TA_CENTER,
                                     textColor=color)),
            Paragraph(label, styles["score_label"]),
        ]

    data = [[
        score_cell(report.overall_score,      "Overall",     overall_color),
        score_cell(report.performance_score,  "Performance", _score_color(report.performance_score)),
        score_cell(report.seo_score,          "SEO",         _score_color(report.seo_score)),
        score_cell(f"{report.load_time_seconds}s", "Load Time", COLOR_GRAY),
    ]]

    # Flatten each cell: list of paragraphs → nested table
    flat_data = [[
        Table([[p] for p in cell], colWidths=["100%"])
        for cell in data[0]
    ]]

    t = Table(flat_data, colWidths=["25%", "25%", "25%", "25%"])
    t.setStyle(TableStyle([
        ("BOX",         (0, 0), (-1, -1), 0.5, HexColor("#e5e7eb")),
        ("INNERGRID",   (0, 0), (-1, -1), 0.5, HexColor("#e5e7eb")),
        ("ROWPADDING",  (0, 0), (-1, -1), 8),
        ("BACKGROUND",  (0, 0), (0, -1),  HexColor("#f5f3ff")),
        ("VALIGN",      (0, 0), (-1, -1), "MIDDLE"),
        ("ROUNDEDCORNERS", [6]),
    ]))
    return [t]


def _build_facts(report, brand: HexColor, styles: dict) -> list:
    """Build the quick facts 3-column grid."""
    facts = [
        ("HTTPS",              "Yes" if report.is_https             else "No",      report.is_https),
        ("Meta Title",         "Present" if report.has_title        else "Missing", report.has_title),
        ("Meta Description",   "Present" if report.has_meta_description else "Missing", report.has_meta_description),
        ("H1 Heading",         "Present" if report.has_h1           else "Missing", report.has_h1),
        ("robots.txt",         "Found"   if report.has_robots_txt   else "Missing", report.has_robots_txt),
        ("XML Sitemap",        "Found"   if report.has_sitemap      else "Missing", report.has_sitemap),
        ("Mobile Friendly",    "Yes"     if report.is_mobile_friendly else "No",    report.is_mobile_friendly),
        ("Broken Links",       f"{report.broken_links_count} found",                report.broken_links_count == 0),
        ("Images Missing Alt", f"{report.images_missing_alt} found",               report.images_missing_alt == 0),
    ]

    rows = []
    for i in range(0, len(facts), 3):
        row = []
        for label, value, ok in facts[i:i+3]:
            indicator = colors.green if ok else colors.red
            cell_table = Table(
                [[Paragraph(f"<b>{label}</b>",
                            ParagraphStyle("fl", fontSize=8.5, fontName="Helvetica-Bold",
                                           textColor=COLOR_BLACK)),
                  Paragraph(value,
                            ParagraphStyle("fv", fontSize=8.5, fontName="Helvetica",
                                           textColor=COLOR_GRAY))]],
                colWidths=["55%", "45%"],
            )
            cell_table.setStyle(TableStyle([
                ("LEFTPADDING",  (0,0), (-1,-1), 8),
                ("RIGHTPADDING", (0,0), (-1,-1), 8),
                ("TOPPADDING",   (0,0), (-1,-1), 6),
                ("BOTTOMPADDING",(0,0), (-1,-1), 6),
                ("LINEAFTER",    (0,0), (0,-1),  0, colors.white),
                ("LINEBEFORE",   (0,0), (0,-1),  3, indicator),
                ("BACKGROUND",   (0,0), (-1,-1), COLOR_LIGHT),
            ]))
            row.append(cell_table)
        # Pad to 3 columns
        while len(row) < 3:
            row.append("")
        rows.append(row)

    t = Table(rows, colWidths=["33.3%", "33.3%", "33.4%"])
    t.setStyle(TableStyle([
        ("VALIGN",      (0, 0), (-1, -1), "TOP"),
        ("ROWPADDING",  (0, 0), (-1, -1), 3),
        ("COLPADDING",  (0, 0), (-1, -1), 3),
    ]))
    return [t]


def _build_category(label: str, items: list, brand: HexColor, styles: dict) -> list:
    """Build one category section with all its check items."""
    elements = []
    elements.append(HRFlowable(width="100%", thickness=1.5, color=brand))
    elements.append(Spacer(1, 1 * mm))
    elements.append(Paragraph(label, styles["section"]))
    elements.append(Spacer(1, 2 * mm))

    for item in items:
        status_color = _status_color(item.status)
        icon = _status_icon(item.status)

        icon_cell = Paragraph(
            f'<font color="#{_color_hex(status_color)}"><b>{icon}</b></font>',
            ParagraphStyle("ic", fontSize=8, fontName="Helvetica-Bold",
                           alignment=TA_CENTER, textColor=status_color),
        )

        content_parts = [Paragraph(item.check_name, styles["check_name"])]
        if item.detail:
            content_parts.append(Paragraph(item.detail, styles["check_detail"]))
        if item.recommendation:
            content_parts.append(Paragraph(f"Tip: {item.recommendation}", styles["check_rec"]))

        content_table = Table([[p] for p in content_parts], colWidths=["100%"])
        content_table.setStyle(TableStyle([
            ("LEFTPADDING",  (0,0), (-1,-1), 0),
            ("RIGHTPADDING", (0,0), (-1,-1), 0),
            ("TOPPADDING",   (0,0), (-1,-1), 1),
            ("BOTTOMPADDING",(0,0), (-1,-1), 1),
        ]))

        row_table = Table(
            [[icon_cell, content_table]],
            colWidths=[12 * mm, None],
        )
        row_table.setStyle(TableStyle([
            ("VALIGN",        (0,0), (-1,-1), "TOP"),
            ("LEFTPADDING",   (0,0), (0,-1),  4),
            ("RIGHTPADDING",  (0,0), (0,-1),  4),
            ("TOPPADDING",    (0,0), (-1,-1), 5),
            ("BOTTOMPADDING", (0,0), (-1,-1), 5),
            ("LINEBEFORE",    (0,0), (0,-1),  3, status_color),
            ("LINEBELOW",     (0,0), (-1,-1), 0.5, COLOR_LIGHT),
        ]))
        elements.append(KeepTogether(row_table))

    return elements


def _color_hex(color: HexColor) -> str:
    """Convert HexColor back to hex string without #."""
    try:
        r = int(color.red * 255)
        g = int(color.green * 255)
        b = int(color.blue * 255)
        return f"{r:02x}{g:02x}{b:02x}"
    except Exception:
        return "6b7280"
