"""Initial database schema

Revision ID: ca2030c47956
Revises: 
Create Date: 2026-08-25 19:29:41.290293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca2030c47956'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('agency_name', sa.String(length=120), nullable=True),
    sa.Column('logo_filename', sa.String(length=255), nullable=True),
    sa.Column('brand_color', sa.String(length=7), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('website_url', sa.String(length=2048), nullable=False),
    sa.Column('contact_email', sa.String(length=254), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('auto_report_enabled', sa.Boolean(), nullable=True),
    sa.Column('auto_report_day', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_user_id'), ['user_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('performance_score', sa.Integer(), nullable=True),
    sa.Column('seo_score', sa.Integer(), nullable=True),
    sa.Column('accessibility_score', sa.Integer(), nullable=True),
    sa.Column('page_speed_mobile', sa.Integer(), nullable=True),
    sa.Column('page_speed_desktop', sa.Integer(), nullable=True),
    sa.Column('load_time_seconds', sa.Float(), nullable=True),
    sa.Column('page_size_kb', sa.Integer(), nullable=True),
    sa.Column('has_title', sa.Boolean(), nullable=True),
    sa.Column('title_text', sa.String(length=512), nullable=True),
    sa.Column('has_meta_description', sa.Boolean(), nullable=True),
    sa.Column('meta_description_text', sa.String(length=512), nullable=True),
    sa.Column('has_h1', sa.Boolean(), nullable=True),
    sa.Column('h1_count', sa.Integer(), nullable=True),
    sa.Column('is_https', sa.Boolean(), nullable=True),
    sa.Column('has_robots_txt', sa.Boolean(), nullable=True),
    sa.Column('has_sitemap', sa.Boolean(), nullable=True),
    sa.Column('is_mobile_friendly', sa.Boolean(), nullable=True),
    sa.Column('broken_links_count', sa.Integer(), nullable=True),
    sa.Column('images_missing_alt', sa.Integer(), nullable=True),
    sa.Column('pdf_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_client_id'), ['client_id'], unique=False)

    op.create_table('report_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('check_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_items_report_id'), ['report_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_items_report_id'))

    op.drop_table('report_items')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_client_id'))

    op.drop_table('reports')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_user_id'))

    op.drop_table('clients')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
